apiVersion: kyverno.io/v1                                                                                                                                                                                                                      
kind: ClusterPolicy
metadata:
  name: allow-linkerd-proxy-injection
spec:
  background: true
  validationFailureAction: enforce  
  rules:
  - match:
      resources:
        kinds:
        - Pod
        - Cronjobs
        - Deployments
        - StatefulSet
        - DaemonSet
        - Job
    name: linkerd-proxy-capabilities
    validate:
      message: Adding of additional capabilities beyond the default set is not allowed.
        The fields spec.containers[*].securityContext.capabilities.add and  spec.initContainers[*].securityContext.capabilities.add
        must be empty.
      pattern:
        spec:
          =(initContainers):
          - =(securityContext):
              =(capabilities): {}
          containers:
          - =(securityContext):
              =(capabilities): {}
            name: "!linkerd-proxy"
